### ISSUE TITLE
Corrupted <PgsSubtitleItem>: Found 65508 bytes for image, but x were expected

### ISSUE THREAD

**Issue by viown** [ratoaq2/pgsrip#11]
I seem to be getting this warning on a lot of separate video files, and the affected subtitle items usually aren't OCR'd correctly at the bottom or sometimes at the right of the image, as if a portion of the image was cut off.

I used --keep-temp-files to check the images, and they're indeed not being displayed correctly:
![image](https://user-images.githubusercontent.com/48097677/217905885-73a60c27-fb10-4ba2-a190-949005b025d8.png)

Playing the video with subtitles on a player like VLC seems to display the subtitles correctly without issues though.

**Comment by viown** [comment]
Okay, so I decided to look into this more to find out why this is happening. It seems that not all image data is loaded when the segment is larger than 2^16 bytes because the segment size defined in the header is limited to 2 bytes, while the object data length can go up to 3. In some cases, when the image is large enough, it'll exceed 2 bytes and why the cut-off happens here: https://github.com/ratoaq2/pgsrip/blob/master/pgsrip/pgs.py#L57 and the warning shows up due to the size mismatch.

Perhaps it would be better to use the data length field when the segment is an Object Definition to determine the true size of the segment and to ensure no cut-off happens?

**Comment by ratoaq2** [comment]
Thanks for the details...
Would you have a sample sup file so I can validate a fix for this?

**Comment by viown** [comment]
[subtitle.zip](https://github.com/ratoaq2/pgsrip/files/10707834/subtitle.zip)

Here you go.

**Comment by ratoaq2** [comment]
Thanks, I had to do a refactoring to handle multipart ODS in order to fix this.
I'm doing a release so you can test if you want

**Comment by ratoaq2** [comment]
For reference:
Initially I used the information about PGS spec from here:
https://blog.thescorpius.com/index.php/2017/07/15/presentation-graphic-stream-sup-files-bluray-subtitle-format/

But, this case was not covered by that and you can find the complete specification here: https://patentimages.storage.googleapis.com/3e/b5/03/01caa801c398a8/US20090185789A1.pdf

**Comment by viown** [comment]
Thank you! I just tested it out and it seems to work flawlessly now.
